data_name: miniImageNet

# base info
way_num: 5
shot_num: 1
query_num: 15
episode_size: 1

# data info
data_root: /data/wzy/miniImageNet--ravi
image_size: 84
use_memory: False
augment: True
augment_times: 1
train_episode: 10000
test_episode: 1000

# train info
epoch: 60

# optimizer info
optimizer:
  name: Adam
  kwargs:
    lr: 0.001
  other:
    model_func: 0.001

# lr_scheduler info
lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 1.0
    step_size: 10

# arch info
backbone:
  name: Conv64F
  kwargs:
    is_flatten: True

classifier:
  name: BaselinePlus
  kwargs:
    inner_optim:
      name: Adam
      kwargs:
        lr: 1e-3
    inner_train_iter: 100
    inner_batch_size: 4
    feat_dim: 1600
    num_classes: 64

# result info
result_root: ./results
save_interval: 10
save_part:
  - model_func
  - classifier

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 1
n_gpu: 1
parallel_part:
  - model_func
seed: 0
deterministic: True










