data_name: miniImageNet

# base info
train_way: 5
train_shot: 5
train_query: 15
episode_size: 1

# data info
data_root: /data/wzy/miniImageNet--ravi
image_size: 84
use_memory: False
augment: True
augment_times: 1
train_episode: 10000
test_episode: 1000

# train info
epoch: 30
test_epoch: 5
resume: False

backbone:
  kwargs:
    is_flatten: false
  name: Conv64FLeakyReLU

classifier:
  kwargs:
    n_k: 3
  name: DN4

# optimizer info
optimizer:
  name: Adam
  kwargs:
    lr: 0.001
    betas:
      - 0.5
      - 0.9
  other:
    model_func: 0.001

# lr_scheduler info
lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.05
    step_size: 10


# result info
result_root: ./results
save_interval: 10
save_part:
  - emb_func
  - dn4_layer

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 3
n_gpu: 1
parallel_part:
  - emb_func
seed: 0
deterministic: True

