#! this is file is under testing
use_loss_yaml: True # todo: option for debugging

# losses is a instance of dict
# it should be :
# losses: {'CrossEntropyLoss':
#


loss:
  name: CrossEntropyLoss
  kwargs:
