epoch: 50
test_epoch: 5

parallel_part:
  - emb_func

pretrain_path: ~
resume: False
# few shot settings
train_way: 5
train_shot: 5
train_query: 15
test_way: ~ # use ~ -> test_* = *_num
test_shot: ~
test_query: ~
episode_size: 1
train_episode: 10000
test_episode: 1000

# general model setting
batch_size: 128