train_episode: 1000
test_episode: 200

save_part:
  - emb_func
device_ids: 0,1,2,3
n_gpu: 4
# arch info
backbone:
  name: Conv64FLeakyReLU
  kwargs:
    is_flatten: False

classifier:
  name: ADM_KL
  kwargs:
    n_k: 3
    CMS: True
