train_episode: 1000
test_episode: 200

save_part:
  - model_func
  - classifier

# arch info
backbone:
  name: Conv64F
  kwargs:
    is_flatten: True

classifier:
  name: ANIL
  kwargs:
    inner_optim:
      name: Adam
      kwargs:
        lr: 1e-3
    inner_train_iter: 10
    feat_dim: 1600
    hid_dim: 800