train_episode: 1000
test_episode: 500

save_part:
  - model_func
  - classifier

# arch info
backbone:
  name: Conv64F
  kwargs:
    is_flatten: True

classifier:
  name: BaselinePlus
  kwargs:
    inner_optim:
      name: Adam
      kwargs:
        lr: 1e-2
    inner_train_iter: 20
    feat_dim: 1600
    num_classes: 64