train_episode: 1200
test_episode: 1000
episode_size: 4

data_root: /data/tiexin/DataSets/miniImageNet

save_part:
  - model_func
  - cam_layer

epoch: 90
way_num: 5
shot_num: 1
query_num: 15

augment_method: RandomFlip

device_ids: 6,7
n_gpu: 2
parallel_part:
  - model_func
  - cam_layer

# arch info
backbone:
  name: resnet12
  kwargs:
    avg_pool: False
    is_flatten: False

classifier:
  name: CAN
  kwargs:
    scale_cls: 7 # default
    nFeat: 640

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 5e-4
    nesterov: True
  other:
    model_func: 0.1
    cam_layer: 0.1

# lr_scheduler info
lr_scheduler:
  name: MultiStepLR
  kwargs:
    milestones: [60,80]
    gamma: 0.05

seed: 1
deterministic: True
