data_name: tieredImageNet
data_root: /data/yxs/tiered_imagenet
result_root: ./results/tieredImageNet/

train_episode: 1200
test_episode: 1000
episode_size: 1

save_part:
  - emb_func
  - cam_layer

epoch: 90
way_num: 5
shot_num: 5
query_num: 15


# arch info
backbone:
  name: resnet18
  kwargs:
    avg_pool: False
    is_flatten: False

classifier:
  name: CAN
  kwargs:
    scale_cls: 7 # default
    num_classes: 351
    nFeat: 512
    HW: 11

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 5e-4
    nesterov: True
  other:
    model_func: 0.01
    cam_layer: 0.01

# lr_scheduler info
lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 90
    eta_min: 0

device_ids: 7
n_gpu: 1
parallel_part:
  - emb_func
  - cam_layer
seed: 0
deterministic: True
