includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/DN4.yaml

way_num: 5
shot_num: 1
query_num: 15
episode_size: 1
train_episode: 2000
test_episode: 600

device_ids: 1
n_gpu: 1
epoch: 100

# loss:
#   name: SoftlabelCrossEntropyLoss
#   kwargs: ~

aug_config:
  train: ~
    # mixup:
    #   mixup_alpha: 0.0
    #   cutmix_alpha: 0.0
    #   cutmix_minmax: ~
    #   mode: episode
    #   label_smoothing: 0.1
    # label_smoothing:
    #   smoothing: 0.1
    #   num_classes: 64

lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 50
  name: StepLR

optimizer:
  kwargs:
    lr: 0.001
  name: Adam

# backbone:
#   name: Conv64F
#   kwargs:
#     is_flatten: False
#     is_feature: False
#     leaky_relu: True
#     negative_slope: 0.2
#     last_pool: False

backbone:
  name: resnet12
  kwargs:
    avg_pool: False
    is_flatten: False

# backbone:
#   name: resnet18
#   kwargs:
#     is_flatten: False
#     avg_pool: False
#     last_block_stride: 1

# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10
#     avg_pool: False
#     is_flatten: False
