train_episode: 10000
test_episode: 600
episode_size: 16

save_part:
  - emb_func

device_ids: 0,1,2,3
n_gpu: 4
parallel_part:
  - emb_func
  - dn4_layer

# arch info
backbone:
  name: Conv64FLeakyReLU
  kwargs:
    is_flatten: False

classifier:
  name: DN4
  kwargs:
    n_k: 3
