data_name: miniImageNet
#data_name: tieredImageNet

# base info
way_num: 5
shot_num: 5
query_num: 15
batch_size: 128
episode_size: 1

# data info
data_root: /data/student/miniImageNet--ravi
#data_root: /data/yxs/tiered_imagenet
image_size: 84
augment: True
augment_times: 1
train_episode: 10000
test_episode: 1000

# train info
epoch: 50

# arch info
pretrain_path: ./results/Baseline-miniImageNet-resnet12-5-1/checkpoints/model_func_best.pth
#pretrain_path: ./results/Baseline-tieredImageNet-resnet18-5-1/checkpoints/model_func_best.pth

#backbone:
#  name: WRN
#  kwargs:
#    depth: 28
#    widen_factor: 10
backbone:
  name: resnet12
  kwargs:
#    avg_pool: True

classifier:
  name: LEO
  kwargs:
    inner_optim:
        inner_lr: 1e-2
        finetune_lr: 1e-2
    inner_train_iter: 5
    finetune_iter: 5
    feat_dim: 640
    hid_dim: 64
    kl_weight: 1e-3
    encoder_penalty_weight: 1e-9
    orthogonality_penalty_weight: 1e-3

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.001
    momentum: 0.9
  other:
    model_func: 0.001

# lr_scheduler info
lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 50
    eta_min: 0

# result info
result_root: ./results
save_interval: 10
save_part:
  - model_func
  - encoder
  - decoder

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 1
n_gpu: 1
parallel_part:
  - model_func
seed: 0
deterministic: False
