data_name: miniImageNet
#data_name: tieredImageNet

# base info
way_num: 5
shot_num: 1
query_num: 15
batch_size: 128
episode_size: 1

# data info
data_root: /data/yxs/miniImageNet--ravi
#data_root: /data/student/tiered_imagenet
image_size: 84
augment: True
augment_times: 1
train_episode: 1000
test_episode: 1000

# train info
epoch: 60

# arch info
pretrain_path: /home/yxs/Codes/LibFewShot/results/Baseline-resnet12-5-5/checkpoints/model_func_best.pth

#backbone:
#  name: WRN
#  kwargs:
#    depth: 28
#    widen_factor: 10
backbone:
  name: resnet12
  kwargs:
    avg_pool: True

classifier:
  name: LEO
  kwargs:
    inner_optim:
        inner_lr: 1e-2
        finetune_lr: 1e-2
    inner_train_iter: 5
    finetune_iter: 5
    feat_dim: 640
    hid_dim: 320

# optimizer info
optimizer:
  name: Adam
  kwargs:
    lr: 0.001
  other:
    model_func: 0.001

# lr_scheduler info
lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 10

# result info
result_root: ./results
save_interval: 10
save_part:
  - model_func
  - classifier

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 1
n_gpu: 1
parallel_part:
  - model_func
seed: 0
deterministic: True
