data_name: miniImageNet

# base info
way_num: 5
shot_num: 1
query_num: 15
batch_size: 128
episode_size: 1

# data info
data_root: /data/wzy/miniImageNet--ravi
image_size: 80
augment_method: MTLAugment
augment: True
augment_times: 1
train_episode: 10000
test_episode: 1000

# train info
epoch: 100

# arch info
backbone:
  name: resnet12MTL
  kwargs:
    MTL: False

classifier:
   name: MTLPretrain
   kwargs:
     feat_dim: 640
     num_class: 64
     inner_train_iter: 100

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: True
  other: ~


# lr_scheduler info
lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.2
    step_size: 30

# result info
result_root: ./results
save_interval: 10
save_part:
  - emb_func

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 0
n_gpu: 1
parallel_part:
  - emb_func
seed: 0
deterministic: True
