train_episode: 10000
test_episode: 600
train_way: 5
train_shot: 1
train_query: 10
batch_size: 1
episode_size: 1
augment_times: 3
augment_times_query: 6

image_size: 84
augment: True

# train info
epoch: 50

includes:
  - headers/yaml_import_test.yaml
  - headers/model.yaml


save_part:
  - emb_func

device_ids: 0,1
n_gpu: 2
parallel_part:
  - emb_func
  - proto_layer

# arch info
backbone:
  name: Conv64F
  kwargs:
    is_flatten: True

classifier:
  name: ProtoNet
  kwargs: ~