includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml

way_num: 5
shot_num: 1
query_num: 15
episode_size: 1
train_episode: 2000
test_episode: 600

device_ids: 0
n_gpu: 1
epoch: 100

# num_workers: 0

seed: ~
deterministic: False

loss:
  name: SoftlabelCrossEntropyLoss
  kwargs: ~

aug_config:
  train:
    mixup:
      mixup_alpha: 0.2
      cutmix_alpha: 0.0
      cutmix_minmax: ~
      mode: episode
      label_smoothing: 0.0

# augment_method: RandAugment
# image_size: 84

lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 20
  name: StepLR
optimizer:
  kwargs:
    lr: 0.001
  name: Adam

# backbone:
#   name: Conv64F
#   kwargs:
#     is_flatten: True
#     is_feature: False
#     leaky_relu: False
#     negative_slope: 0.2
#     last_pool: True

backbone:
  name: resnet12
  kwargs: ~

# backbone:
#   name: resnet18
#   kwargs:

# backbone:
#   name: WRN
#   kwargs:
#     depth: 10
#     widen_factor: 10
#     dropRate: 0.0
#     avg_pool: True
#     is_flatten: True

# optimizer:
#   name: AdamW
#   kwargs:
#     lr: 1e-3
#     weight_decay: 5e-2
#   other: ~

# lr_scheduler:
#   name: CosineAnnealingLR
#   kwargs:
#     T_max: 200
#     eta_min: 0

# # backbone:
# #   name: CvT
# #   kwargs: ~

# backbone:
#   name: swin_mini
#   kwargs:
#     hidden_dim: 16
#     window_size: 7
#     pool: False
#     layers:
#       - 2
#       - 2
#       - 10
#       - 2
#     heads:
#       - 1
#       - 2
#       - 2
#       - 4
#     downscaling_factors:
#       - 3
#       - 2
#       - 2
#       - 1

# backbone:
#   name: ViT
#   kwargs:
#     image_size: 84
#     patch_size: 28
#     dim: 1024
#     depth: 6
#     heads: 16
#     mlp_dim: 640
#     dropout: 0.1
#     emb_dropout: 0.1