data_name: miniImageNet

# base info
way_num: 5
shot_num: 1
query_num: 15
batch_size: 128
episode_size: 1

# data info
data_root: /data/yxs/miniImageNet--ravi
image_size: 84
use_memory: False
augment: True
augment_times: 1
train_episode: 10000
test_episode: 1000

# train info
epoch: 50
test_epoch: 5
resume: False


backbone:
  name: Conv64FLeakyReLU
  kwargs:
    is_flatten: False

classifier:
  name: RelationNet
  kwargs:
    feat_dim: 64
    feat_height: 3
    feat_width: 3

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.01
  other:

# lr_scheduler info
lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 50
    eta_min: 0

# result info
result_root: ./results
save_interval: 10
save_part:
  - emb_func
  - relation_layer

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 2
n_gpu: 1
parallel_part:
  - emb_func
  - relation_layer
seed: 0
deterministic: False
