data_name: miniImageNet

# base info
train_way: 5
train_shot: 5
train_query: 15
batch_size: 128
episode_size: 5

# data info
data_root: /data/dcq/DataSets/miniImageNet
image_size: 84
use_memory: False
augment: True
augment_times: 1
train_episode: 5000
test_episode: 1000

# train info
epoch: 50
test_epoch: 5
resume: False

save_part:
  - emb_func
  - classifier


# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 0, 1
n_gpu: 2
parallel_part:
  - emb_func
  - classifier
  - distill_layer
seed: 1
deterministic: True

# arch info
backbone:
  name: Conv64F
  kwargs:
    is_flatten: True

classifier:
  name: RFSModel
  kwargs:
    feat_dim: 1600
    num_class: 64
    gamma: 0.5
    alpha: 0.5
    is_distill: True
    model_func_path: ./results/RFSModel-Conv64F-5-5/checkpoints/model_func_best.pth
    classifier_path: ./results/RFSModel-Conv64F-5-5/checkpoints/classifier_best.pth