data_name: miniImageNet
#data_name: tieredImageNet

# base info
way_num: 5
shot_num: 1
query_num: 15
batch_size: 128
episode_size: 1

# data info
data_root: /data/yxs/miniImageNet--ravi
#data_root: /data/student/tiered_imagenet
image_size: 84
use_memory: False
augment: True
augment_times: 1
train_episode: 10000
test_episode: 1000

# train info
epoch: 60
test_epoch: 5
resume: False

# arch info
#backbone:
#  name: Conv64F
#  kwargs:
#    is_flatten: True

backbone:
  name: resnet12
  kwargs: ~


classifier:
  name: VERSA
  kwargs:
    feat_dim: 640
    hid_dim: 640
    sample_num: 10

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.0005
    weight_decay: 0.0005
  other:

# lr_scheduler info
lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 100
    eta_min: 0

# result info
result_root: ./results
save_interval: 10
save_part:
  - emb_func
  - weight_means
  - weight_logvars
  - bias_means
  - bias_logvars

# log info
log_level: info
log_interval: 100

# gpu info
device_ids: 2
n_gpu: 1
parallel_part:
  - emb_func
  - weight_means
  - weight_logvars
  - bias_means
  - bias_logvars
  - head
seed: 0
deterministic: False

